// Auto-generated by optimized_matching pipeline
// Generated: 2025-12-01T07:17:57
// Function index for D2 Version Archive (Split Format)
// Load per-file data from functions/<filename>.<group>.js

var FUNCTION_INDEX = {
  "generated": "2025-12-01T07:17:57",
  "split_format": true,
  "groups": [
    "pre",
    "post",
    "lod"
  ],
  "group_names": {
    "pre": "Pre-Refactor (1.00-1.03)",
    "post": "Post-Refactor (1.04+)",
    "lod": "Lord of Destruction"
  },
  "files": {
    "Binkw32.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 139,
          "versions": 4,
          "size": 29406
        },
        "post": {
          "count": 106,
          "versions": 20,
          "size": 72135
        },
        "lod": {
          "count": 106,
          "versions": 15,
          "size": 50217
        }
      }
    },
    "Bnclient.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 179,
          "versions": 4,
          "size": 27546
        },
        "post": {
          "count": 1069,
          "versions": 16,
          "size": 150830
        },
        "lod": {
          "count": 942,
          "versions": 11,
          "size": 120142
        }
      }
    },
    "D2CMP.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 391,
          "versions": 4,
          "size": 73070
        },
        "post": {
          "count": 430,
          "versions": 16,
          "size": 114607
        },
        "lod": {
          "count": 405,
          "versions": 11,
          "size": 83062
        }
      }
    },
    "D2Client.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 2180,
          "versions": 4,
          "size": 415115
        },
        "post": {
          "count": 8802,
          "versions": 16,
          "size": 1227657
        },
        "lod": {
          "count": 7080,
          "versions": 11,
          "size": 896759
        }
      }
    },
    "D2Common.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 2558,
          "versions": 4,
          "size": 503856
        },
        "post": {
          "count": 2775,
          "versions": 16,
          "size": 888697
        },
        "lod": {
          "count": 2589,
          "versions": 11,
          "size": 628317
        }
      }
    },
    "D2DDraw.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 42,
          "versions": 4,
          "size": 8857
        },
        "post": {
          "count": 106,
          "versions": 16,
          "size": 19698
        },
        "lod": {
          "count": 88,
          "versions": 11,
          "size": 14165
        }
      }
    },
    "D2Direct3D.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 88,
          "versions": 4,
          "size": 15781
        },
        "post": {
          "count": 274,
          "versions": 16,
          "size": 42035
        },
        "lod": {
          "count": 228,
          "versions": 11,
          "size": 30890
        }
      }
    },
    "D2Game.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 2283,
          "versions": 4,
          "size": 434641
        },
        "post": {
          "count": 5658,
          "versions": 16,
          "size": 858422
        },
        "lod": {
          "count": 4560,
          "versions": 11,
          "size": 606598
        }
      }
    },
    "D2Gdi.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 35,
          "versions": 4,
          "size": 7441
        },
        "post": {
          "count": 152,
          "versions": 16,
          "size": 27484
        },
        "lod": {
          "count": 92,
          "versions": 11,
          "size": 15720
        }
      }
    },
    "D2Gfx.dll": {
      "function_count": 2678,
      "version_count": 31
    },
    "D2Glide.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 173,
          "versions": 4,
          "size": 27935
        },
        "post": {
          "count": 251,
          "versions": 16,
          "size": 38597
        },
        "lod": {
          "count": 206,
          "versions": 11,
          "size": 28894
        }
      }
    },
    "D2Lang.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 127,
          "versions": 4,
          "size": 23781
        },
        "post": {
          "count": 173,
          "versions": 16,
          "size": 51882
        },
        "lod": {
          "count": 160,
          "versions": 11,
          "size": 35914
        }
      }
    },
    "D2Launch.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 151,
          "versions": 4,
          "size": 27191
        },
        "post": {
          "count": 688,
          "versions": 16,
          "size": 95168
        },
        "lod": {
          "count": 508,
          "versions": 11,
          "size": 64842
        }
      }
    },
    "D2MCPClient.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 124,
          "versions": 4,
          "size": 22658
        },
        "post": {
          "count": 199,
          "versions": 16,
          "size": 56484
        },
        "lod": {
          "count": 149,
          "versions": 11,
          "size": 36812
        }
      }
    },
    "D2Multi.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 164,
          "versions": 4,
          "size": 26146
        },
        "post": {
          "count": 544,
          "versions": 16,
          "size": 78070
        },
        "lod": {
          "count": 405,
          "versions": 11,
          "size": 53115
        }
      }
    },
    "D2Net.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 88,
          "versions": 4,
          "size": 15411
        },
        "post": {
          "count": 108,
          "versions": 16,
          "size": 32204
        },
        "lod": {
          "count": 81,
          "versions": 11,
          "size": 20635
        }
      }
    },
    "D2Server.dll": {
      "function_count": 256,
      "version_count": 1
    },
    "D2Sound.dll": {
      "function_count": 1897,
      "version_count": 31
    },
    "D2VidTst.exe": {
      "function_count": 1563,
      "version_count": 31
    },
    "D2Win.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 399,
          "versions": 4,
          "size": 78763
        },
        "post": {
          "count": 434,
          "versions": 16,
          "size": 143674
        },
        "lod": {
          "count": 409,
          "versions": 11,
          "size": 102321
        }
      }
    },
    "Diablo II.exe": {
      "function_count": 61,
      "version_count": 39
    },
    "Fog.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 447,
          "versions": 4,
          "size": 87197
        },
        "post": {
          "count": 762,
          "versions": 16,
          "size": 204109
        },
        "lod": {
          "count": 681,
          "versions": 11,
          "size": 145808
        }
      }
    },
    "Game.exe": {
      "split": true,
      "groups": {
        "pre": {
          "count": 28,
          "versions": 2,
          "size": 4388
        },
        "post": {
          "count": 18676,
          "versions": 18,
          "size": 2672027
        },
        "lod": {
          "count": 18641,
          "versions": 12,
          "size": 2529274
        }
      }
    },
    "Ijl11.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 51,
          "versions": 4,
          "size": 10680
        },
        "post": {
          "count": 51,
          "versions": 20,
          "size": 34737
        },
        "lod": {
          "count": 51,
          "versions": 15,
          "size": 24039
        }
      }
    },
    "SmackW32.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 78,
          "versions": 4,
          "size": 16720
        },
        "post": {
          "count": 78,
          "versions": 20,
          "size": 53251
        },
        "lod": {
          "count": 78,
          "versions": 15,
          "size": 37045
        }
      }
    },
    "Storm.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 521,
          "versions": 4,
          "size": 110250
        },
        "post": {
          "count": 1790,
          "versions": 16,
          "size": 419564
        },
        "lod": {
          "count": 1723,
          "versions": 11,
          "size": 313173
        }
      }
    },
    "D2gfx.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 199,
          "versions": 4,
          "size": 38879
        },
        "post": {
          "count": 206,
          "versions": 16,
          "size": 64138
        },
        "lod": {
          "count": 193,
          "versions": 11,
          "size": 45711
        }
      }
    },
    "D2sound.dll": {
      "split": true,
      "groups": {
        "pre": {
          "count": 129,
          "versions": 4,
          "size": 27329
        },
        "post": {
          "count": 154,
          "versions": 16,
          "size": 55759
        },
        "lod": {
          "count": 148,
          "versions": 11,
          "size": 38595
        }
      }
    }
  }
};
