#!/usr/bin/env python3
"""
Export Single Version DLL

Creates viewer-compatible export for DLLs that only exist in one version.
This bypasses the matching requirement by directly using analysis data.

Usage:
    python tools/export_single_version.py --dll D2Server.dll --version "Classic/1.00"
"""

import argparse
import json
import time
from pathlib import Path


def export_single_version(project_root: Path, dll_name: str, version: str, ghidra_path: Path = None):
    """Export a single-version DLL for the viewer."""

    # Paths
    analysis_cache = project_root / "cache" / "analysis"
    functions_dir = project_root / "reports" / "functions"
    functions_dir.mkdir(parents=True, exist_ok=True)

    # Find the analysis file - format is cache/analysis/{version_underscore}/{dll}.json
    safe_version = version.replace("/", "_").replace("\\", "_")
    version_dir = analysis_cache / safe_version
    analysis_path = version_dir / f"{dll_name}.json"

    # Try to find it with case-insensitive match
    if not analysis_path.exists() and version_dir.exists():
        for f in version_dir.iterdir():
            if f.name.lower() == f"{dll_name.lower()}.json":
                analysis_path = f
                break

    if not analysis_path.exists():
        print(f"[!] Analysis file not found: {analysis_path}")
        print(f"    Run: python -m tools.optimized_matching.pipeline_runner analyze --dll {dll_name}")
        return

    print(f"[*] Loading analysis: {analysis_path}")
    with open(analysis_path, 'r', encoding='utf-8') as f:
        analysis = json.load(f)

    # Load Ghidra names if available
    ghidra_names = {}
    if ghidra_path is None:
        ghidra_path = project_root / "data" / "ghidra_names" / f"{dll_name}.json"

    if ghidra_path.exists():
        print(f"[*] Loading Ghidra names: {ghidra_path}")
        with open(ghidra_path, 'r', encoding='utf-8') as f:
            ghidra_data = json.load(f)

        ghidra_base = int(ghidra_data.get('image_base', '0'), 16)
        analysis_base = analysis.get('image_base', 0)

        # Build RVA-based lookup
        for addr_str, func_data in ghidra_data.get('functions', {}).items():
            addr = int(addr_str, 16)
            rva = int(func_data.get('rva', '0'), 16)
            name = func_data.get('name', '')
            if name and not name.startswith('FUN_'):
                ghidra_names[rva] = {
                    'name': name,
                    'signature': func_data.get('signature', ''),
                }

        print(f"    Loaded {len(ghidra_names)} named functions from Ghidra")

    # Build functions dictionary
    functions = {}
    func_dict = analysis.get('functions', {})
    image_base_str = analysis.get('image_base', '0x0')
    image_base = int(image_base_str, 16) if isinstance(image_base_str, str) else image_base_str

    print(f"[*] Processing {len(func_dict)} functions...")

    # Sort by address for consistent ordering
    sorted_addrs = sorted(func_dict.keys(), key=lambda x: int(x, 16))

    for i, addr_str in enumerate(sorted_addrs):
        func = func_dict[addr_str]
        addr = int(addr_str, 16)

        # Calculate RVA
        rva_str = func.get('rva', '0')
        rva = int(rva_str, 16) if isinstance(rva_str, str) else rva_str

        func_id = f"func_{i+1:05d}"

        # Get name from exports first, then Ghidra
        name = func.get('export_name')
        ordinal = func.get('export_ordinal')

        if name and name.startswith('Ordinal_'):
            try:
                ordinal = int(name.split('_')[1])
            except:
                pass

        # Check Ghidra names by RVA
        if rva in ghidra_names:
            ghidra_func = ghidra_names[rva]
            if not name or name.startswith('Ordinal_') or name.startswith('FUN_'):
                name = ghidra_func['name']

        # Fallback to func_id
        if not name:
            name = func_id

        functions[func_id] = {
            "name": name,
            "ordinal": ordinal,
            "addresses": {
                version: f"0x{addr:08x}"
            },
            "confidence": 1.0,
            "tier": 0,  # Single version - no matching
        }

    # Count named functions
    named_count = sum(1 for f in functions.values() if not f['name'].startswith('func_'))

    # Build viewer data
    viewer_data = {
        "versions": [version],
        "functions": functions,
    }

    # Write JavaScript file
    safe_name = dll_name.replace('.', '_').replace(' ', '_')
    output_path = functions_dir / f"{dll_name}.js"

    js_content = f"""// Auto-generated by export_single_version.py
// Generated: {time.strftime("%Y-%m-%dT%H:%M:%S")}
// Single-version export for {dll_name} ({version})
// Format: {{versions: [...], functions: {{"key": {{name, ordinal, addresses}}, ...}}}}

var FUNCTIONS_{safe_name.upper()} = {json.dumps(viewer_data, separators=(',', ':'))};
"""

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"[OK] Exported {len(functions)} functions ({named_count} named) to {output_path}")

    # Update index
    update_viewer_index(project_root, dll_name, len(functions), 1)

    return functions


def update_viewer_index(project_root: Path, dll_name: str, func_count: int, version_count: int):
    """Update the reports/functions/_index.js."""
    index_path = project_root / "reports" / "functions" / "_index.js"

    index_data = {
        "generated": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "version_count": version_count,
        "versions": [],
        "files": {}
    }

    if index_path.exists():
        try:
            content = index_path.read_text(encoding='utf-8')
            start = content.find('{')
            if start >= 0:
                existing = json.loads(content[start:].rstrip().rstrip(';'))
                index_data = existing
        except Exception as e:
            print(f"[!] Could not parse existing index: {e}")

    index_data['files'][dll_name] = {
        "function_count": func_count,
        "version_count": version_count,
    }
    index_data['generated'] = time.strftime("%Y-%m-%dT%H:%M:%S")

    js_content = f"""// Auto-generated by optimized_matching pipeline
// Generated: {index_data['generated']}
// Function index for D2 Version Archive
// Load per-file data from functions/<filename>.js

var FUNCTION_INDEX = {json.dumps(index_data, separators=(',', ':'))};
"""
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"[*] Updated index: {index_path}")


def main():
    parser = argparse.ArgumentParser(description="Export single-version DLL for viewer")
    parser.add_argument("--dll", required=True, help="DLL name (e.g., D2Server.dll)")
    parser.add_argument("--version", required=True, help="Version string (e.g., Classic/1.00)")
    parser.add_argument("--ghidra", help="Path to Ghidra names JSON (optional)")

    args = parser.parse_args()

    project_root = Path(__file__).parent.parent
    ghidra_path = Path(args.ghidra) if args.ghidra else None

    export_single_version(project_root, args.dll, args.version, ghidra_path)


if __name__ == "__main__":
    main()
