// Auto-generated Ghidra rename script
// Source: d2moo_known_functions.csv
// Generated by apply_csv_renames.py

// D2Common - 1.10
renameFunction("0x6FDA6790", "MONSTERS_ApplyClassicScaling");
renameFunction("0x6FDAC270", "PATH_ComputePathOrSlideAlongObstacles");
renameFunction("0x6FDABAC0", "PATH_FindSubpathWithoutObstacles");
renameFunction("0x6FDAC170", "PATH_SimplifyToLines");

// D2Common - 1.13c
renameFunction("0x6FD5DDC0", "D2Common_10231_Impl");
renameFunction("0x6FD51250", "DATATBLS_GetSkillsTxtRecord");
renameFunction("0x6FDA3780", "DATATBLS_NewTreasureClassEx");
renameFunction("0x6FDA4430", "DATATBLS_ParseTreasureClassItem");
renameFunction("0x6FDCB220", "PATH_AStar_PopBestScoreForVisit");
renameFunction("0x6FDCB2C0", "PATH_AStar_TargetLocationHasEnoughRoom");
renameFunction("0x6FDC0650", "PATH_IDAStar_FlushNodeToDynamicPath");
renameFunction("0x6FDC0BB0", "PATH_IdaStar_ComputePathWithRooms");
renameFunction("0x6FD85E00", "PATH_PreparePathTargetForPathUpdate");
renameFunction("0x6FD5DC80", "PATH_StopMovement");
renameFunction("0x6FD7FAC0", "UNITS_AnimModeAllowsAnimSpeed");
renameFunction("0x6FD80BD0", "UNITS_CanAnimModeUseAttackRate");
renameFunction("0x6FD80BD0", "UNITS_CanAnimModeUseVelocityModifier");
renameFunction("0x6FD7EF90", "UNITS_IsAnimModeBlocking");
renameFunction("0x6FD7EFC0", "UNITS_IsAnimModeGetHit");
renameFunction("0x6FD7F010", "UNITS_IsAnimModeKnockBack");
renameFunction("0x6FD80B80", "UNITS_IsSeqAnimSpeedModulatedByFCR");
renameFunction("0x6FD5CEB0", "sub_6FD5CEB0");
renameFunction("0x6FD5DB70", "sub_6FD5DB70");
renameFunction("0x6FDC0840", "sub_6FDC0840");

// D2Game - 1.00
renameFunction("0x100056D0", "GAME_ReceiveDatabaseCharacter");

// D2Game - 1.10
renameFunction("0x6FC34A80", "EVENT_FreeEventQueue");
renameFunction("0x6FC36280", "GAME_ReceiveDatabaseCharacter");

// D2Game - 1.13c
renameFunction("0x6FCAE540", "EVENT_AllocateTimer");
renameFunction("0x6FC89B00", "OBJMODE_GetToHitPercentage");

// D2Win - 1.10
renameFunction("0x6F8AFDC0", "D2Win_10043_TEXTBOX_Destroy");
